name: todo-infra-dev-deploy

# Controls when the workflow will run
on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: terraform init and plan
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_USE_OIDC: true

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login #Used OIDC to login to azure
        uses: azure/login@v2.3.0
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID}}

      - name: Terraform Init
        run: |
          terraform init \
          -backend-config="resource_group_name=rg-digwi-terraform-remote" \
          -backend-config="storage_account_name=stgdigwiterraformstate" \
          -backend-config="container_name=tfstate" \
          -backend-config="key=todo-dev.tfstate"

      - name: Terraform Plan
        run: |
          terraform plan -var-file="./environments/dev/dev.tfvars" -out=tfplan

      - name: Terraform Apply
        run: |
          terraform apply -var-file="./environments/dev/dev.tfvars" tfplan
